name: loungees_theme
description: "Loungees 테마 패키지 - 브랜드 컬러, 테마, 스타일 정의"
version: 1.0.0+1
publish_to: "none" # Private package

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
