// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcyvXWlltTnpPEjPeO1zM0cEfS6-bNVI',
    appId: '1:295380669772:web:ee2a671ea74ba0e835ebe9',
    messagingSenderId: '295380669772',
    projectId: 'loungees-49897',
    authDomain: 'loungees-49897.firebaseapp.com',
    storageBucket: 'loungees-49897.firebasestorage.app',
    measurementId: 'G-LSQVM86N52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHfsdeckeYNjchs2QK230deLRAL5OikDM',
    appId: '1:295380669772:android:e7b3d3eb8e61e94035ebe9',
    messagingSenderId: '295380669772',
    projectId: 'loungees-49897',
    storageBucket: 'loungees-49897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmJSZiaPfTOegHxDzm850EWd-qVBPY-o',
    appId: '1:295380669772:ios:53aaf3b40e68c3eb35ebe9',
    messagingSenderId: '295380669772',
    projectId: 'loungees-49897',
    storageBucket: 'loungees-49897.firebasestorage.app',
    iosBundleId: 'com.example.loungeesSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmJSZiaPfTOegHxDzm850EWd-qVBPY-o',
    appId: '1:295380669772:ios:53aaf3b40e68c3eb35ebe9',
    messagingSenderId: '295380669772',
    projectId: 'loungees-49897',
    storageBucket: 'loungees-49897.firebasestorage.app',
    iosBundleId: 'com.example.loungeesSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqcyvXWlltTnpPEjPeO1zM0cEfS6-bNVI',
    appId: '1:295380669772:web:8b0f4dc10d5b6e7735ebe9',
    messagingSenderId: '295380669772',
    projectId: 'loungees-49897',
    authDomain: 'loungees-49897.firebaseapp.com',
    storageBucket: 'loungees-49897.firebasestorage.app',
    measurementId: 'G-ZCHX53XKYN',
  );
}
